### ISSUE TITLE
add to openSUSE open build service?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [jameysharp/autobake#1]
Porting packages over seems like the primary challenge for the Nix community, and `autobake` seems like an awesome step in the right direction.
It'd be nice tho if we could make this easier still by letting devs better consider Nix compatibility, by e.g. adding something like autobake to openSUSE's [open build service](https://github.com/openSUSE/open-build-service), to get build status on the radar of devs who might not even be familiar with Nix.
I'm not even sure what's needed for this (nixpkgs/hydra?), and maybe this is more of a thread for nixpkgs, but kinda curious how you'd think about this.

**Comment by jameysharp** [comment]
Sorry for not responding! Someday I will convince GitHub to actually tell me when people open issues on my projects.

I haven't looked at OBS in years, but taking a quick look at it now, it looks to me like they expect developers to provide appropriate packaging (e.g. a `.spec` file to build an RPM). So I think the Nix equivalent would be providing a `.nix` file with a suitable derivation. I think it'd be weird to give Nix special treatment with autobake in that setting.

But, the problem I created autobake to address certainly isn't Nix-specific, and I think it'd be fantastic if every distro that OBS supports had autobake support integrated there as well. Developers use OBS because they don't have all those distros installed and can't tell whether their stuff will work across all those variations, right? Seems natural to me that they wouldn't know what package names to use as dependencies in every case either, so this tool would be helpful for targeting any distro.

If this kind of auto-packaging service were part of OBS generally, then I think it would make a lot of sense to encourage them to also do it for Nix. At that point developers would be expecting to build packages using package managers they know nothing about anyway. Give 'em a template with some blank values in `meta` and let them run with it.

I don't think getting any of this into OBS is an issue to discuss here, so I'm going to go ahead and close this issue. But I'd love to take pull requests providing autobake implementations for the package managers and distributions that OBS supports. That in turn might make it feasible to get OBS to add this to their tooling, which would be a conversation to have on their issue tracker. Even if that didn't work out, each step along the way would be useful.

**Comment by KiaraGrouwstra** [comment]
Thanks! I opened an issue on [their end](https://github.com/openSUSE/open-build-service/issues/9488) to get their take. So the first concern seems to be to expand support over here from Nix to their supported package formats.
I understand that the present repo is more of a PoC, but for whoever might be interested in this, as per OBS's [docs](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html) their supported package formats seem to include:
- RPM: Spec
- Debian: Dsc
- Arch: pkg
- KIWI Appliance
- SimpleImage
- AppImage
